#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Project: SocialBit TikTok CSV Import Optimization

set -e

echo "========================================"
echo "SocialBit Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Configuration
PROJECT_DIR="C:/xampp3/htdocs/socialbit-live"
XAMPP_DIR="C:/xampp3"

# ============================================
# CHECK XAMPP SERVICES
# ============================================

echo ""
echo "Checking XAMPP services..."

# Check Apache
if curl -s -o /dev/null -w "%{http_code}" http://localhost/socialbit-live/ | grep -q "200\|302"; then
    echo -e "${GREEN}Apache is running${NC}"
else
    echo -e "${YELLOW}Apache may not be running - please start XAMPP${NC}"
    echo "  Run: $XAMPP_DIR/xampp-control.exe"
fi

# Check MySQL
if mysql -u root -e "SELECT 1" &>/dev/null; then
    echo -e "${GREEN}MySQL is running${NC}"
else
    echo -e "${YELLOW}MySQL may not be running - please start XAMPP${NC}"
    echo "  Run: $XAMPP_DIR/xampp-control.exe"
fi

# ============================================
# VERIFY DATABASE
# ============================================

echo ""
echo "Checking database..."

mysql -u root -e "USE social_media_analytics; SELECT COUNT(*) as posts_count FROM posts;" 2>/dev/null && \
    echo -e "${GREEN}Database 'social_media_analytics' exists${NC}" || \
    echo -e "${YELLOW}Database may not be initialized - run schema script${NC}"

# ============================================
# PHP SYNTAX CHECK
# ============================================

echo ""
echo "Checking PHP syntax..."

cd "$PROJECT_DIR"

if php -l src/Services/GenericCsvImporter.php 2>&1 | grep -q "No syntax errors"; then
    echo -e "${GREEN}GenericCsvImporter.php: OK${NC}"
else
    echo -e "${RED}GenericCsvImporter.php: SYNTAX ERROR${NC}"
fi

if php -l src/Services/TikTokCsvImporter.php 2>&1 | grep -q "No syntax errors"; then
    echo -e "${GREEN}TikTokCsvImporter.php: OK${NC}"
else
    echo -e "${RED}TikTokCsvImporter.php: SYNTAX ERROR${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Check Complete!"
echo "========================================"
echo ""
echo "Services:"
echo "  Application: http://localhost/socialbit-live/"
echo "  API Base:    http://localhost/socialbit-live/api/"
echo ""
echo "Key Endpoints:"
echo "  POST /api/import/tiktok  - Legacy TikTok importer"
echo "  POST /api/import/csv     - Generic CSV importer"
echo ""
echo "Files to Modify:"
echo "  src/Services/GenericCsvImporter.php  (primary)"
echo "  src/Services/TikTokCsvImporter.php   (secondary)"
echo "  src/Controllers/ImportController.php (optional)"
echo ""
echo "Test Commands:"
echo "  curl -X POST -F 'file=@test.csv' http://localhost/socialbit-live/api/import/csv"
echo ""
